### PR TITLE
feat(header): 🚀 info over header titles via tooltip added

### PR DESCRIPTION
**Pull request by onuralpszr**
# Description

I added better explanation for each header show what it means to make people learn and understand better way, it will show If you wait 700 ms 

-   [X] New feature (non-breaking change which adds functionality)

Light/Dark theme perspective 

image
image

### CODE REVIEW

**Review by LinasKo — CHANGES_REQUESTED** [review]
I like the idea.

One change request: it should be obvious that the header is clickable. We have a sort icon right now, but I'd also like to remove `$('th').css('cursor', 'help');` as it feels a bit confusing.

**Comment by onuralpszr** [comment]
@LinasKo  I removed it.

**Review by LinasKo — APPROVED** [review]
Looks great now! I especially like that the colors are different in light and dark modes :)

**Comment by onuralpszr** [comment]
> Looks great now! I especially like that the colors are different in light and dark modes :)

Yup, we  have all the theme supports :)

**Pull request merged**
